apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: monitor-api
  namespace: pulse-check
spec:
  ingressClassName: traefik
  rules:
    - host: monitor.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: monitor-api
                port:
                  number: 80 
