{
 "title": "Monitor-api-health",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Availability over time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "probe_up", "legendFormat": "{{target}}" }
   ]
  },
  {
   "title": "Enabled targets count",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "monitor_enabled_targets", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "In-flight probe executions",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "probe_runs_in_flight", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "probe_up", "legendFormat": "{{target}}" }
   ]
  },
  {
   "title": "Average Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum by (target) (rate(probe_latency_ms_sum[5m])) / sum by(target) (rate(probe_latency_ms_count[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Volume",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (target, status) (rate(probe_requests_total[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "P95 Probe Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (le, target) (rate(probe_latency_ms_bucket[5m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Last successfull probe",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsLocal" } },
   "targets": [
    { "expr": "probe_last_success_timestamp", "legendFormat": "{{target}}" }
   ]
  },
  {
   "title": "Scheduler queue size",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "scheduler_queue_size", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Error rate",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(probe_requests_total{status=\"error\"}[15m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}